aspnet_core_hw2_Dushkevych/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class Address
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Zip { get; set; }
        public int UserId { get; set; }
    }
}

aspnet_core_hw2_Dushkevych/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public string CreatedAt { get; set; }
        public string Body { get; set; }
        public int UserId { get; set; }
        public int PostId { get; set; }
        public int Likes { get; set; }
    }
}

aspnet_core_hw2_Dushkevych/Models/ErrorViewModel.cs
using System;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aspnet_core_hw2_Dushkevych/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string CreatedAt { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int UserId { get; set; }
        public int Likes { get; set; }
        public List<Comment> Comments { get; set; }
        public string Username { get; set; }
    }
}

aspnet_core_hw2_Dushkevych/Models/Todo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class Todo
    {
        public int Id { get; set; }
        public string CreatedAt { get; set; }
        public string Name { get; set; }
        public bool IsComplete { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
    }
}

aspnet_core_hw2_Dushkevych/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnet_core_hw2_Dushkevych.Models
{
    public class User
    {
        public int Id { get; set; }
        public string CreatedAt { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public string Email { get; set; }
        public List<Post> Posts { get; set; }
        public List<Todo> Todos { get; set; }
        public Address Address { get; set; }
    }
}

aspnet_core_hw2_Dushkevych/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspnet_core_hw2_Dushkevych.Models;

namespace aspnet_core_hw2_Dushkevych.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aspnet_core_hw2_Dushkevych/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspnet_core_hw2_Dushkevych.Models;
using aspnet_core_hw2_Dushkevych.Services;

namespace aspnet_core_hw2_Dushkevych.Controllers
{
    public class PostController : Controller
    {
        private DataService dataService;
        private List<Post> posts;
        public PostController()
        {
            dataService = new DataService();
        }

        public IActionResult Index()
        {
            posts = dataService.GetPosts();
            foreach (var post in posts)
            {
                post.Username = dataService.GetUserNameById(post.UserId);
                post.Comments = dataService.GetPostComments(post.Id);
            }
            return View(posts);
        }

        public IActionResult PostDetails(int id)
        {
            var post = dataService.GetPostById(id);
            post.Username = dataService.GetUserNameById(post.UserId);
            return View(post);
        }
    }
}

aspnet_core_hw2_Dushkevych/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspnet_core_hw2_Dushkevych.Models;
using aspnet_core_hw2_Dushkevych.Services;

namespace aspnet_core_hw2_Dushkevych.Controllers
{
    public class TodoController : Controller
    {
        private DataService dataService;
        private List<Todo> todos;
        public TodoController()
        {
            dataService = new DataService();
        }

        public IActionResult Index()
        {
            todos = dataService.GetTodos();
            foreach(var todo in todos)
            {
                todo.Username = dataService.GetUserNameById(todo.UserId);
            }
            return View(todos);
        }

        public IActionResult TodoDetails(int id)
        {
            var todo = dataService.GetTodoById(id);
            todo.Username = dataService.GetUserNameById(todo.UserId);
            return View(todo);
        }
    }
}

aspnet_core_hw2_Dushkevych/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspnet_core_hw2_Dushkevych.Models;
using aspnet_core_hw2_Dushkevych.Services;

namespace aspnet_core_hw2_Dushkevych.Controllers
{
    public class UserController : Controller
    {
        private DataService dataService;
        public UserController()
        {
            dataService = new DataService();
        }

        public IActionResult Index(int id)
        {
            User user = dataService.GetUserById(id);
            user.Address = dataService.GetUserAddress(user.Id);
            return View(user);
        }
    }
}

aspnet_core_hw2_Dushkevych/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspnet_core_hw2_Dushkevych.Models;
using aspnet_core_hw2_Dushkevych.Services;

namespace aspnet_core_hw2_Dushkevych.Controllers
{
    public class UsersController : Controller
    {
        private DataService dataService;
        private List<User> users;
        public UsersController()
        {
            dataService = new DataService();
        }

        public IActionResult Index()
        {
            users = dataService.GetUsers();
            foreach(User user in users)
            {
                user.Posts = dataService.GetUserPosts(user.Id);
                user.Todos = dataService.GetUserTodos(user.Id);
            }
            return View(users);
        }
    }
}

aspnet_core_hw2_Dushkevych/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

aspnet_core_hw2_Dushkevych/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

aspnet_core_hw2_Dushkevych/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

aspnet_core_hw2_Dushkevych/Views/Post/Index.cshtml
@model IEnumerable<aspnet_core_hw2_Dushkevych.Models.Post>

@{
    ViewData["Title"] = "Index";
}

<h2> Posts </h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Body)
                </th>
                <th>
                    Username
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Likes)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @item.CreatedAt.Substring(0, 10);
            </td>
            <td>
                <a asp-controller="Post" asp-action="PostDetails" asp-route-id="@item.Id">@item.Title</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                <a asp-controller="User" asp-action="Index" asp-route-id="@item.UserId">@item.Username</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Likes)
            </td>
        </tr>
}
    </tbody>
</table>

aspnet_core_hw2_Dushkevych/Views/Post/PostDetails.cshtml
@model aspnet_core_hw2_Dushkevych.Models.Post

@{
    ViewData["Title"] = "PostDetails";
}

<h2>Post @Model.Title</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Model.CreatedAt.Substring(0, 10);
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Likes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Likes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            <a asp-controller="User" asp-action="Index" asp-route-id="@Model.UserId">@Model.Username</a>
        </dd>
    </dl>
</div>

aspnet_core_hw2_Dushkevych/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspnet_core_hw2_Dushkevych</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">aspnet_core_hw2_Dushkevych</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    <li><a asp-area="" asp-controller="Todo" asp-action="Index">Todos</a></li>
                    <li><a asp-area="" asp-controller="Post" asp-action="Index">Posts</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - aspnet_core_hw2_Dushkevych</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

aspnet_core_hw2_Dushkevych/Views/Todo/Index.cshtml
@model IEnumerable<aspnet_core_hw2_Dushkevych.Models.Todo>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsComplete)
                </th>
                <th>
                    Username
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @item.CreatedAt.Substring(0, 10);
            </td>
            <td>
                <a asp-controller="Todo" asp-action="TodoDetails" asp-route-id="@item.Id">@item.Name</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsComplete)
            </td>
            <td>
                <a asp-controller="User" asp-action="Index" asp-route-id="@item.UserId">@item.Username</a>
            </td>
        </tr>
}
    </tbody>
</table>

aspnet_core_hw2_Dushkevych/Views/Todo/TodoDetails.cshtml
@model aspnet_core_hw2_Dushkevych.Models.Todo

@{
    ViewData["Title"] = "TodoDetails";
}

<h2>TodoDetails</h2>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> Id </dt>
        <dd> @Model.Id </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            <a asp-controller="User" asp-action="Index" asp-route-id="@Model.UserId">@Model.Username</a>
        </dd>
    </dl>
</div>

aspnet_core_hw2_Dushkevych/Views/User/Index.cshtml
@model aspnet_core_hw2_Dushkevych.Models.User
@{
    ViewData["Title"] = "Index";
}

<h2>User @Model.Name</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <img src="@Model.Avatar" alt="@Model.Name" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-9">
                        <h4>
                            @Model.Name
                        </h4>
                        <small>
                            <cite title="@Model.Address.City">
                                <i class="glyphicon glyphicon-map-marker"></i> @Model.Address.City, @Model.Address.Country, @Model.Address.Zip
                    </cite>
                    </small>
                    <p>
                        <i class="glyphicon glyphicon-envelope"></i> @Model.Email
                        <br />
                        <i class="glyphicon glyphicon-gift"></i> Created at: @Model.CreatedAt
                    </p>
                    <div class="btn btn-group">
                        <button type="button" class="btn btn-primary" data-toggle="collapse" href="#collapsePosts" aria-expanded="false" aria-controls="collapsePosts"> Posts </button>
                        <button type="button" class="btn btn-primary" data-toggle="collapse" href="#collapseComments" aria-expanded="false" aria-controls="collapseComments"> Todos </button>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="collapse multi-collapse" id="collapsePosts">
                                <div class="card card-body">
                                    <div class="row">
                                        <div class="col-md-8"><strong>Title</strong></div>
                                        <div class="col-md-4"><strong>Likes</strong></div>
                                    </div>
                                    <hr />
                                    @foreach (var post in Model.Posts)
                                    {
                                        <div class="row">
                                            <div class="col-md-8"><a asp-controller="Post" asp-action="PostDetails" asp-route-id="@post.Id">@post.Title</a></div>
                                            <div class="col-md-4">@post.Likes</div>
                                        </div>
                                    }
                                    <hr />
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="collapse multi-collapse" id="collapseComments">
                                <div class="card card-body">
                                    <div class="row">
                                        <div class="col-md-8"><strong>Todo</strong></div>
                                        <div class="col-md-4"><strong>Is complete</strong></div>
                                    </div>
                                    <hr />
                                    @foreach (var todo in Model.Todos)
                                    {
                                        <div class="row">
                                            <div class="col-md-8"><a asp-controller="Todo" asp-action="TodoDetails" asp-route-id="@todo.Id">@todo.Name</a></div>
                                            <div class="col-md-4">
                                                @if (todo.IsComplete)
                                                {
                                                    <span class="badge badge-success">Completed</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-danger">Incomplete</span>
                                                }
                                            </div>
                                        </div>
                                    }
                                    <hr />
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

aspnet_core_hw2_Dushkevych/Views/Users/Index.cshtml
@model List<aspnet_core_hw2_Dushkevych.Models.User>
@{
    ViewData["Title"] = "Index";
}

<h2>User list</h2>
<table class="table table-responsive table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Picture</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Posts</th>
            <th scope="col">Todos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
        <tr>
            <th scope="row">@user.Id</th>
            <td><img src="@user.Avatar" alt="@user.Name" /></td>
            <td><a asp-controller="User" asp-action="Index" asp-route-id="@user.Id">@user.Name</a></td>
            <td>@user.Email</td>
            <td>@user.Posts.Count</td>
            <td>@user.Todos.Count</td>
            @*<td data-toggle="collapse" data-target="#collapsePosts" class="glyphicon-plus" aria-expanded="false" aria-controls="collapsePosts"></td>*@
        </tr>
        
        @*<tr id="collapsePosts" class="collapse">
            <tr>
                <tr class="post">
                    <th>Username</th>
                    <th>Body</th>
                    <th>Likes</th>
                </tr>
                <tr class="todo">
                    <th>Name</th>
                    <th>Completed</th>
                </tr>
            </tr>
            
            
        </tr>*@
        
        }
    </tbody>
</table>